### ISSUE TITLE
Tema: Po-Ui: A jornada da criação de um Design System Open Source

### ISSUE THREAD

**Issue by alvarocamillont** [hacktoberfestbrasil/2020#3]
Vamos falar sobre o PoUI, o primeiro grande projeto totalmente open source da TOTVS, além dos detalhes técnicos, vamos contar como foi o processo de concepção e da abertura de código desse Design System.
Essa palestra será sobre o case do Po-Ui, um Design System Open Source mantido pela TOTVS mas disponível para todos através da licença MIT. Irei conversar como foi a jornada desde o inicio do THF até se tornar o Po-Ui.
Não só o projeto foi feito com uma intensa pesquisa de UX como a abertura do seu código também, além do desafio de convencer a diretoria em tornar o projeto Open Source.

**Comment by guiseek** [comment]
muito bom Alvaro!! tema animal obrigado por participar!
